### ISSUE TITLE
`RuntimeError: No route to host` when using torch.distributed

### ISSUE THREAD

**Issue by currymj** [facebookincubator/gloo#219]
I am trying to run PyTorch-BigGraph (which uses torch distributed) on a Slurm cluster, using the gloo backend with TCP initialization,  but consistently get a `RuntimeError: No route to host`. After building a minimal working example that just uses simple torch.distributed functions, it seems like this occurs in situations where `init_process_group` is called for a rank >0 process before it has been called for the rank 0 process. If I force the rank 0 process to call `init_process_group` first, the bug seems to disappear and everybody can happily connect.

The whole saga is here: https://github.com/facebookresearch/PyTorch-BigGraph/issues/99

I am told that this is not expected behavior -- it should be fine to just let all the processes call `init_process_group` and wait for the rank 0 process to come up.

I can post the code for a working example, but I'm not sure it would do much good -- it would have to run on a Slurm cluster, perhaps even this specific Slurm cluster.

Has anyone run into anything like this in the past? Any guess as to why it might be happening? Things to try to narrow it down further?

(Also, it may be the result of some unusual network configuration on this cluster -- any sense of what sorts of things I might ask the cluster administrators about?)

**Comment by pietern** [comment]
This is not really a Gloo issue either, tbh, but more a PyTorch issue. 

What happens is that the default initialization method (`env`, see [initialization](https://pytorch.org/docs/stable/distributed.html#initialization)) will start a simple TCP based key/value server on rank 0 and tries to connect to that server on the other ranks. If there is a skew in the start time of these processes, the non-zero ranks will gracefully retry the connection, if they get either a "connection refused" error (in case rank 0 hasn't started yet), or a "connection reset" error (in case too many ranks are connecting at the same time and some have to back off for a bit). Both of these assume there is network connectivity between all ranks. 

The "no route to host" error means that the non-zero ranks can't even send a packet to rank 0, because there are no routes for its IP in the local machine's routing table. I assume the system you're working with has sets up these routes as the job starts, which would explain why you see "no route to host" if rank 0 hasn't started yet, but not if it has. Usually, this error is permanent and not transient, which is why I'm hesitant to make the connect function retry for this error as well.

What you can do for the time being is catch the error and retry yourself. A simple backoff mechanism should do the trick, as long as you filter the right error.

Check out https://pypi.org/project/retrying/ for example.

cc @lerks

**Comment by pietern** [comment]
As far as what to ask the cluster administrators about: I'd try and confirm if it's accurate that a job's routes are only setup once a rank has been started (and by extension, perhaps, if there is a single routing table entry for every task in the job).

**Comment by pietern** [comment]
I'm closing this issue here, since there is nothing in Gloo that we can do about this.
