### ISSUE TITLE
Is it possible to use Gloo without redis?

### ISSUE THREAD

**Issue by awan-10** [facebookincubator/gloo#32]
I am trying to run the benchmark but I don't want to use Redis. 

Is it possible to use just MPI to create the context and then run the included benchmark using mpirun or mpiexec?

I tried building without the redis by setting -DUSE_REDIS=0 but the cmake step fails. Is Redis a required dependency for Gloo?

**Comment by pietern** [comment]
It's required for the benchmark at this point, haven't made it runnable through MPI yet.

I guess it wouldn't be too hard to modify it. If you add some ifdefs around the Redis specific code in the benchmark code and conditionally add MPI support from `gloo/mpi` then you should be set. Is this something you would be interested in contributing?

**Comment by ammarawan** [comment]
Hi Pieter, thank you for your response. 

Do you mean redis is required to build the benchmark or is it required to even run it? 

I actually tried running it using MVAPICH2 but ran into some issues. I am a little occupied with some other things at the moment but will get back to this soon. 

With IB-transport, I saw some hang in the pollCompletions(). 
With TCP transport, I saw some output but there were some errors at finalize. 

Please see the run command and the output below.

mpirun_rsh -export -np 2 gpu01 gpu17 ./bin/benchmark --inputs=2 --transport=ibverbs --size=2 --elements=10 broadcast_one_to_all

**Goes to hang with ibverbs:**
Device:      ibverbs, pci=, dev=mlx5_0, port=1, index=1
Algorithm:   broadcast_one_to_all
Options:     processes=2, inputs=2

   elements   min (us)   p50 (us)   p99 (us)   max (us)    samples

**Runs with tcp but crashes:**
Device:      tcp, pci=0000:81:00.0, iface=en0, speed=1000, addr=[10.1.1.1]
Algorithm:   broadcast_one_to_all
Options:     processes=2, inputs=2

   elements   min (us)   p50 (us)   p99 (us)   max (us)    samples
         10          1          1         50        102     262020
Attempting to use an MPI routine after finalizing MPICH
Attempting to use an MPI routine after finalizing MPICH
[gpu01.cluster:mpispawn_0][child_handler] MPI process (rank: 0, pid: 8525) exited with status 1
[gpu17.cluster:mpispawn_1][child_handler] MPI process (rank: 1, pid: 22612) exited with status 1

One general question/comment I have is about Gloo's motivation and how it compares to MPI-based collectives in OpenMPI/MVAPICH2? I mean both these MPI libraries use InfiniBand and they do provide CUDA-Aware MPI interfaces to do collective communication on GPUs as well. How Gloo is different and why/when MPI cannot be used as is and Gloo becomes essential?

**Comment by pietern** [comment]
Redis is required to run the benchmark. The participating nodes need to be able to find each other and there is no MPI support right now. It's possible to add it by optionally depending on the code in `gloo/mpi` and using that for rendezvous.

I assume you did these changes in order to run it through mpirun, otherwise you wouldn't have gotten those results :+1: 

Regarding the hangs, that's something to investigate further... I have not seen the hangs on the ibverbs transport myself, but have only tested using Mellanox cards with RoCE support, not pure IB NICs. Another possibility might be subtle differences in the ibverbs API?

Regarding your general question: Gloo implements the same collectives as whatever flavor of MPI you pick so functionally it is equivalent. The main differences are:

1. Lines of code (we try to keep Gloo as small as possible)
2. Pre-initialization of algorithms vs ad-hoc execution (avoids unnecessary memcpy's)
3. Failure handling (node failures can be bubbled up to the application, which can replace the failed node or re-rendezvous and continue with a smaller number of nodes, or crash, whatever is applicable)

A little more history: we've had some trouble using MPI in Facebook's IPv6-only environment (I upstreamed a patch to OpenMPI for this), and problems launching jobs (since we can't use mpirun as is). We still needed to use collective primitives, so ended up implementing the bare minimum to do socket based peer to peer communication. This then grew into the project you see today. While it started as a way to get around the problems we had getting OpenMPI to work, it has since allowed us to implement new algorithms, pipelining techniques, and made it easier to deal with machine failure.

**Comment by ammarawan** [comment]
Pieter, thanks a lot for your detailed response and the history of Gloo. 

I think the hang is expected then since the benchmark is not supposed to run without Redis. But I am not sure how the TCP transport is working fine with MPI only. 

Btw, I didn't do any changes to the benchmark code. I only did a small fix to the context.cc code in the gloo/mpi folder to workaround a sanity check in MPICH/MVAPICH that doesn't allow an in-place Allreduce without specifying MPI_IN_PLACE. 

Please see the diff below. Other than this, I haven't touched the code. I just passed the correct mpicc and mpicxx path and add -DUSE_MPI=1 to the cmake command.

diff --git a/gloo/mpi/context.cc b/gloo/mpi/context.cc
index 15b2a54..9106b03 100644
--- a/gloo/mpi/context.cc
+++ b/gloo/mpi/context.cc
@@ -65,8 +65,7 @@ void Context::connectFullMesh(std::shared_ptr<transport::Device>& dev) {
   }
 
   // Agree on maximum length so we can prepare buffers
-  rv = MPI_Allreduce(
-    &maxLength, &maxLength, 1, MPI_UNSIGNED_LONG, MPI_MAX, comm_);
+  rv = MPI_Allreduce(MPI_IN_PLACE, &maxLength, 1, MPI_UNSIGNED_LONG, MPI_MAX, comm_);
   if (rv != MPI_SUCCESS) {
     GLOO_THROW_IO_EXCEPTION("MPI_Allreduce: ", rv);
   }

**Comment by pietern** [comment]
Following up on this. The Redis dependency for the benchmark is now gone. You can compile with `USE_REDIS=OFF` and `USE_MPI=ON` and the benchmark tool will run fine when run through MPI.

**Comment by pietern** [comment]
This is the relevant pull request: #55.

**Comment by awan-10** [comment]
@pietern - thanks for following up. I will try to run the benchmark with MPI only. 

Btw, do you plan to make the change I suggested about MPI_IN_PLACE in the MPI_Allreduce?

**Comment by pietern** [comment]
@awan-10 Yes, I'll do that next.

By the way, I found you also need #56 to make the build work without Redis (runtime was already fine if you had the hiredis library around to make the build work).
