### ISSUE TITLE
how to obtain communication time

### ISSUE THREAD

**Issue by githubgsq** [facebookincubator/gloo#71]
hi, @pietern how to count communication time when program run with gloo on multiple nodes?
what about nccl? 
Is there any method to seperate computation time from nccl communication time and communication time produced among different nodes please?

**Comment by githubgsq** [comment]
@pietern I run caffe2 on a single machine reasonably, but when it runs on multiple nodes, the speed is very slow. I'm not sure whether it is caused by gloo communication, then I think the problem may be analyzed  by comparing the communication time and computation time, but I don't how to test.
I run caffe2 resnet50 example.
Is there any advice please?

**Comment by pietern** [comment]
You can use the [prof_dag_net](https://github.com/caffe2/caffe2/blob/master/caffe2/contrib/prof/prof_dag_net.h) in Caffe2 to get a report of the time spent in each operator. The allreduce operator captures both local reduction and communication time.

You can also run the Gloo benchmark tool for a microbenchmark of allreduce over various buffer sizes. See the [benchmarking](https://github.com/facebookincubator/gloo#benchmarking) subsection of the README for more information on how to do that.

Closing this issue, because there is no reason to believe there is a bug. It is possible you're using slow ethernet cards in your tests (for example 1Gbit/sec).

**Comment by githubgsq** [comment]
Thanks a lot !
